[tools]
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
node = "26"
oxfmt = "latest"
pnpm = "11"

[env]
PGTZ = "UTC"
PGDATABASE = "duongondro_dev"
DATABASE_URL = "postgres://postgres:postgres@localhost:5432/{{ env.PGDATABASE }}?options=-c%20TimeZone%3DUTC"

GOOSE_DBSTRING = "{{ env.DATABASE_URL }}"
GOOSE_DRIVER = "postgres"
GOOSE_MIGRATION_DIR = "src/db/migrations"

# openssl rand -base64 64 | tr -d '\n'
SECRET_KEY_BASE = "N/PzP+Ed0ptrkx+bLG+M7b1PV/sqtYu4tbRv605IfyxAeeyeQoVdEciYo6hfgoDlZhkHLCfBkOnl/iKEcreDVg=="

[tasks."db:seed"]
run = """
#!/usr/bin/env -S bash -euo pipefail

for file in src/db/seeds/*.sql; do
  psql $DATABASE_URL -f $file
done
"""

[tasks."db:setup"]
run = """
#!/usr/bin/env -S bash -euo pipefail

mise db:create
goose up
mise db:seed
"""

[tasks."db:create"]
run = """
#!/usr/bin/env -S bash -euo pipefail

db_exists="$(psql --csv -t postgres postgres -c "select exists (select from pg_database where datname = '$PGDATABASE')")"

if [[ $db_exists = f ]]; then
  createdb
fi
"""

[tasks."db:reset"]
run = """
#!/usr/bin/env -S bash -euo pipefail

db_exists="$(psql --csv -t postgres postgres -c "select exists (select from pg_database where datname = '$PGDATABASE')")"

if [[ $db_exists = t ]]; then
  dropdb $PGDATABASE
fi

mise db:setup
"""
